### ISSUE TITLE
lzma_decode failed

### ISSUE THREAD

**Issue by maxl95** [victhor393/openwrt-ruckus-r500#1]
Hey Victhor,

i followed the instructions of your wiki to flash my R500. Unfortunately i get a "lzma_decode failed" when try to boot the initram. 
What do you mean with "So you need to generate images without dictionary." ? Is that perhaps the reason for my error?
Is it possible to share your precompiled initram & squashfs with me? 

Best regards maxl95

`u-boot> bootlcl 0x88000000
RKS Header: load_address=0x80060000
RKS Header: offset=0xa0, entry=0x80060000, len=5179580
properties(0x18736)*sizeof(CProb)(0x2) > 0x9000
lzma_decode failed. res=1, len=0
: @ 880000a0 (88000000 + a0) size=5179580 -> 80060000`

**Comment by maxl95** [comment]
So here is my workaround for the lzma_decode error.

i copied the initram WITHOUT header modification via tftp:
`tftpboot 0x88000000`
after that:
`bootm 0x88000000`
and now the initram should boot up. 

I backuped my ART partition and follow the instructions.

Thank you very much for this port. it helped me alot.

**Comment by victhor393** [comment]
Hi, thanks for providing a solution, I really should update the wiki, that is indeed the right command to boot a initramfs image. The reason the lzma decode fails is because the image size on the header needs to be changed.

There is another person working on this OpenWrt port, with a few updates (including proper factory images): https://github.com/dmascord/openwrt/tree/add_ruckus_r500
You should check it out.

Sorry for responding so late, but I had notifications disabled on this repository!!! I don't monitor issues manually. Apparently that's the default setting for own repositories...
